ALTER TABLE CAR_MODEL ADD COLUMN HEIGHT INT;

CREATE TABLE IF NOT EXISTS ENGINE (
      ID INT NOT NULL AUTO_INCREMENT
    , CAR_MODEL_ID INT NOT NULL REFERENCES CAR_MODEL (ID) on delete cascade
    , NAME VARCHAR(100) NOT NULL
    , HEIGHT INT NOT NULL
    , NUMBER_OF_CYLINDERS INT NOT NULL
    , CAPACITY INT NOT NULL
    , PRIMARY KEY (ID)
    );